global tile specific flag to get things to cleanly shut down
firedancer-io/firedancer pull request #1529
Opened 2024-04-18 15:44 UTC by jumpsiegel

This is a process specific shutdown for tiles/threads.  This should be integrated with other shutdown standards with the goal of cleanly shutting down the entire system

2024-04-18 15:51 UTC, mmcgee-jump requested changes
I think fd_tile is probably not the right place for this shutdown flag. Exiting the executing task seems to be the model that's already supported by the code as written, (e.g. via the tile CNC) and supports threading / process models used by both 1.5 and other jump teams internally when calling this util code.

2024-04-18 15:57 UTC, jumpsiegel commented
What are your specific recommended changes?  What is the correct API we should call for setting a shutdown request and/or checking to see if it is set?

2024-04-18 16:06 UTC, mmcgee-jump commented
I think the design of tile exec, and tpool exec as intended is that clean exit is done by the child task that's executing returning to the parent, not by the parent simply halting execution. There are a few reasons that design is better.

You can conform to that design by exiting tiles with the CNC object (changing it into the shutdown state), and adding a specific flag for worker items of the tpool which have long loops you want to be able to exit during the loop. Many worker items wouldn't need it, since they exit reasonably quickly anyway.

2024-04-18 17:10 UTC, jumpsiegel commented
I also agree... this cross object/abstraction boundries in inconsistent ways.

2024-04-19 13:53 UTC, asiegel-jt commented
Regardless the scratch changes are needed to get a leak free shutdown

2024-04-19 15:18 UTC, ripatel-fd commented
I'm going to close this for now since clean shutdown is possible without 'low-level' modifications to tpool.

2024-04-19 15:18 UTC, closed without merging