[wip] VM Belt Sanding
firedancer-io/firedancer pull request #1624
Opened 2024-04-24 16:49 UTC by topointon-jump

Tracking branch for vm belt sanding. Will merge after all ledger tests are passing.

2024-06-23 22:04 UTC, ripatel-fd commented
Converting this to draft due to merge conflicts.

2024-06-24 14:51 UTC, ibhatt-jumptrading approved these changes

2024-06-24 15:28 UTC, ravyu-jump requested changes

2024-06-24 15:28 UTC, ravyu-jump commented on src/app/fdctl/version.h
> +#define FDCTL_MAJOR_VERSION 0UL
this file is autogenerated and should not be checked in

2024-06-24 15:53 UTC, mmcgee-jump commented on config/extra/with-tracing.mk
> +CFLAGS+=-DFD_DEBUG_SBPF_TRACES=1
Newline eof

2024-06-24 15:53 UTC, mmcgee-jump commented on contrib/test/run_test_vectors.sh
> +fi
Newline eof

2024-06-24 16:12 UTC, ravyu-jump approved these changes

2024-06-24 17:47 UTC, jumpsiegel approved these changes

2024-06-24 17:47 UTC, merged