tiles: add gossip tile to mainnet
firedancer-io/firedancer pull request #1639
Opened 2024-04-25 16:45 UTC by lheeger-jump

2024-04-25 18:09 UTC, arjain4 requested changes

2024-04-25 22:02 UTC, lheeger-jump commented on src/app/fdctl/run/tiles/fd_gossip.c
> +static inline void
Yes we can do this in follow up

2024-04-25 22:13 UTC, lheeger-jump commented on src/app/fdctl/run/tiles/fd_gossip.c
> +
done

2024-04-26 02:49 UTC, arjain4 requested changes
Final changes i think

2024-04-26 02:49 UTC, arjain4 commented on src/app/fdctl/run/tiles/fd_gossip.c
> +struct __attribute__((packed)) fd_shred_dest_wire {
These have been shifted out to util in the repair PR, just as a note

2024-04-26 02:49 UTC, arjain4 commented on src/app/fdctl/run/tiles/fd_gossip.c
> +
nit: random whitespace

2024-04-26 02:49 UTC, arjain4 commented on src/app/fdctl/run/tiles/fd_gossip.c
> +  return 4096UL;
is 4096 required? Might work with 128

2024-04-26 02:49 UTC, arjain4 commented on src/app/fdctl/run/tiles/fd_gossip.c
> +            ulong              in_idx,
FD_PARAM_UNUSED is the way to go it turns out :)

2024-04-26 02:49 UTC, arjain4 commented on src/app/fdctl/run/tiles/fd_gossip.c
> +  .mux_flags                = FD_MUX_FLAG_COPY,
Does this need a manual publish flag? My understanding is that we don't need to publish every time

2024-04-29 20:13 UTC, asiegel-jt approved these changes

2024-04-30 19:07 UTC, mmcgee-jump commented on src/disco/topo/fd_topo.h
> +      char    gossip_peer_addr[ 22 ]; // len('255.255.255.255:65535') == 22
uint gossip_peer_ip_addr;

2024-05-06 20:05 UTC, closed without merging