disable_optimizer: disable optimization via environmental variable
firedancer-io/firedancer pull request #1644
Opened 2024-04-25 19:18 UTC by jumpsiegel

2024-04-25 19:42 UTC, mmcgee-jump requested changes
Thank you! Very useful

2024-04-25 19:42 UTC, mmcgee-jump commented on config/extra/with-optimization.mk
> +ifeq ($(DISABLE_OPTIMIZATION),)
```suggestion
ifeq ($(FD_DISABLE_OPTIMIZATION),)
```

2024-04-26 11:43 UTC, jumpsiegel commented on config/extra/with-optimization.mk
> +ifeq ($(DISABLE_OPTIMIZATION),)
good suggestion.. done

2024-04-26 16:10 UTC, mmcgee-jump approved these changes

2024-04-26 16:56 UTC, merged