Add test_consensus in disco
firedancer-io/firedancer pull request #1665
Opened 2024-04-29 15:09 UTC by yhzhangjump

2024-04-29 15:34 UTC, lidatong requested changes
looks good so far, see comments

2024-04-29 15:34 UTC, lidatong commented on src/disco/consensus/test_consensus.h
> +static int
i would just put these at the top of `test_consensus.c` and remove the `.h` altogether

2024-04-29 15:38 UTC, yhzhangjump commented on src/disco/consensus/test_consensus.c
> +    goto archive_online;
Totally agree. I will put all the common setup pieces before this if/else.

2024-05-03 15:41 UTC, lidatong approved these changes

2024-05-07 18:07 UTC, lidatong submitted a review, later dismissed

2024-05-07 19:16 UTC, lidatong approved these changes

2024-05-07 19:37 UTC, merged