flamenco: frank ledger overhaul
firedancer-io/firedancer pull request #1688
Opened 2024-04-30 19:18 UTC by ibhatt-jumptrading

1. Refactor
2. Adding command to swap out blocks from a checkpoint
3. Adding replay directly from frank_ledger

2024-05-01 21:53 UTC, lheeger-jump requested changes
more testing is required

2024-05-01 22:21 UTC, ibhatt-jumptrading commented
> more testing is required

tested every command thoroughly

2024-05-02 10:19 UTC, jumpsiegel approved these changes

2024-05-02 13:39 UTC, jumpsiegel approved these changes

2024-05-02 13:45 UTC, jumpsiegel approved these changes

2024-05-02 15:44 UTC, asiegel-jt approved these changes
Move tpool construction/destruction/worker push into runtime_replay

2024-05-02 17:11 UTC, lheeger-jump submitted a review, later dismissed

2024-05-02 18:03 UTC, jumpsiegel submitted a review, later dismissed

2024-05-02 19:17 UTC, jumpsiegel approved these changes

2024-05-02 19:23 UTC, merged