flamenco: bpf loader rewrite
firedancer-io/firedancer pull request #1905
Opened 2024-05-17 18:10 UTC by ibhatt-jumptrading

very wip, not at all working or ready for review

2024-05-22 20:55 UTC, ibhatt-jumptrading commented on src/flamenco/runtime/program/fd_bpf_loader.c
because its wrong

2024-05-22 20:56 UTC, ibhatt-jumptrading commented on src/flamenco/runtime/program/fd_bpf_loader.c
following the naming convention provided by agave client

2024-05-23 21:07 UTC, ibhatt-jumptrading commented on src/flamenco/runtime/program/fd_bpf_loader.c
> +  fd_valloc_free( instr_ctx->valloc, rodata );
Yep this was just from copying over from the old implementation 🙂

2024-05-23 21:21 UTC, ibhatt-jumptrading commented on src/flamenco/runtime/program/fd_bpf_loader_v3_program.h
>  read_bpf_upgradeable_loader_state_for_program( fd_exec_txn_ctx_t * txn_ctx,
This needs to get refactored and cleaned up, but leaving for now as it's used in other parts of the codebase. It serves the same funciton as `read_bpf_upgradeable_loader_state_for_program`

2024-05-28 13:48 UTC, topointon-jump reviewed
Mid-way through reviewing, will finish by EOD. Feel free to ignore these comments or address in a follow-up PR :)

2024-05-28 14:34 UTC, topointon-jump requested changes
The sysvar account checks are consensus-critical, do you mind addressing before merging? 🙏

2024-05-29 10:39 UTC, topointon-jump requested changes
Overall looks great! Spotted a few consensus-critical things

2024-05-29 10:39 UTC, topointon-jump commented on src/flamenco/runtime/program/fd_bpf_loader_v3_program.c
> +  FD_SCRATCH_SCOPE_BEGIN {
You could also just have a single `FD_SCRATCH_SCOPE_[BEGIN,END]` in `fd_bpf_loader_v3_program_execute`, which might be cleaner.

2024-05-29 10:39 UTC, topointon-jump commented on src/flamenco/runtime/program/fd_bpf_loader_v3_program.c
> +      if( err ) {
```suggestion
      if( FD_UNLIKELY( err ) ) {
```

Do you mind adding this hint to all the conditionals as appropriate?

2024-05-29 10:39 UTC, topointon-jump commented on src/flamenco/runtime/program/fd_bpf_loader_v3_program.c
> +      signers[ 1UL ] = *programdata_key;
These signers look wrong - Agave uses these keys as seeds to derive signer PDA's from, not the keys themselves: https://github.com/anza-xyz/agave/blob/574bae8fefc0ed256b55340b9d87b7689bcdf222/programs/bpf_loader/src/lib.rs#L638-L641

2024-05-29 10:39 UTC, topointon-jump commented on src/flamenco/runtime/program/fd_bpf_loader_v3_program.c
Where are these checks in Agave? These don't line up with the source - do you mind adding a permalink 🙏

2024-05-29 10:39 UTC, topointon-jump commented on src/flamenco/runtime/program/fd_bpf_loader_v3_program.c
> +    programdata->meta->info.rent_epoch = 0UL;
Where are these checks in Agave? These don't line up with the source - do you mind adding a permalink 🙏

2024-05-29 13:49 UTC, topointon-jump commented on src/flamenco/runtime/program/fd_bpf_loader_v3_program.c
> +        FD_LOG_WARNING(( "Buffer authority is not optional" ));
```suggestion
        FD_LOG_WARNING(( "Buffer authority is not optional" ));
        return FD_EXECUTOR_INSTR_ERR_INCORRECT_AUTHORITY;
```

2024-05-29 13:52 UTC, topointon-jump commented on src/flamenco/runtime/program/fd_bpf_loader_v3_program.c
> +      account_state.inner.program_data.upgrade_authority_address = new_authority;
```suggestion
      account_state.inner.program_data.upgrade_authority_address = new_authority;
      account_state.inner.program_data.slot = clock.slot;
```

2024-05-29 13:58 UTC, topointon-jump commented on src/flamenco/runtime/program/fd_bpf_loader_v3_program.c
> +      account_state.inner.program_data.upgrade_authority_address = (fd_pubkey_t*)new_authority_key;
```suggestion
      account_state.inner.program_data.upgrade_authority_address = (fd_pubkey_t*)new_authority_key;
      account_state.inner.program_data.slot = clock.slot;
```

2024-05-29 14:09 UTC, topointon-jump commented on src/flamenco/runtime/program/fd_bpf_loader_v3_program.c
> +           is unitialized. */
Agave delays the visibility of program deployments: whenever a program is un-/re-/deployed, it becomes unavailable for the rest of the transaction. They do this by modifying the cache entry. Do we have these same semantics?

(See https://github.com/solana-labs/solana/pull/29654 and `delay_visibility_of_program_deployment`)

2024-05-29 14:12 UTC, topointon-jump requested changes
Found a few more consensus-critical issues - almost there 😄

2024-05-29 14:42 UTC, topointon-jump commented on src/flamenco/runtime/program/fd_bpf_loader_v3_program.c
> +           is unitialized. */
We will add ledger tests for this

2024-05-29 16:14 UTC, topointon-jump requested changes
Last consensus-critical bug 🎉

2024-05-29 16:14 UTC, topointon-jump commented on src/flamenco/runtime/program/fd_bpf_loader_v3_program.c
> +    }
Agave doesn't pass any signers: https://github.com/anza-xyz/agave/blob/574bae8fefc0ed256b55340b9d87b7689bcdf222/programs/bpf_loader/src/lib.rs#L1250-L1254

2024-05-29 16:15 UTC, topointon-jump commented on src/flamenco/runtime/program/fd_bpf_loader_v3_program.c
> +    }
Looks like GitHub put this comment in the wrong place - I was referring to https://github.com/firedancer-io/firedancer/blob/00bf781b080b7a37ac82bf4b588048d31ba820bb/src/flamenco/runtime/program/fd_bpf_loader_v3_program.c#L1321-L1322

2024-05-30 11:26 UTC, topointon-jump requested changes
Last round of review! The PDA bug should definitely be fixed before merging 🙏

2024-05-30 11:26 UTC, topointon-jump commented on src/flamenco/runtime/program/fd_bpf_loader_v3_program.c
> +    err = fd_instr_borrowed_account_modify_idx( instr_ctx, 0UL, 0UL, &payer );
We should use `fd_borrowed_account_acquire_write`/`fd_borrowed_account_acquire_read`/`fd_borrowed_account_release_write`/`fd_borrowed_account_release_read` like we do in the other native programs.

We can move to the scoping macro in a follow-up PR.

2024-05-30 11:26 UTC, topointon-jump commented on src/flamenco/runtime/fd_pubkey_utils.c
> +  }
This iteration is wrong - we should hash all the seeds, then hash the bump seed, then hash the program id, then hash the marker. This loop hashes the bump seed, program id and marker every time.

See https://github.com/firedancer-io/firedancer/blob/vm-belt-sanding-public/src/flamenco/vm/syscall/fd_vm_syscall_pda.c#L12-L69

2024-05-30 14:01 UTC, ibhatt-jumptrading commented on src/flamenco/runtime/program/fd_bpf_loader_v3_program.c
> +    fd_pubkey_t const *     program_id      = &ctx.instr->program_id_pubkey;
committing with the same version that matches the rest of my commits

2024-05-30 14:23 UTC, topointon-jump submitted a review, later dismissed
🎉

2024-05-30 14:54 UTC, merged