gossip: use the same gossip listen port value everywhere
firedancer-io/firedancer pull request #1944
Opened 2024-05-23 21:02 UTC by arjain4

Closes #1942

2024-05-23 21:44 UTC, llamb-jump submitted a review, later dismissed

2024-05-23 21:53 UTC, mmcgee-jump commented on src/app/fdctl/configure/xdp.c
> +    config->gossip.port,
This change (already) breaks 1.5 since you are going to intercept gossip traffic from reaching the agave code, even when running 1.5 topology.

2024-05-23 21:53 UTC, mmcgee-jump requested changes
.

2024-05-24 13:11 UTC, asiegel-jt approved these changes

2024-05-24 13:19 UTC, lheeger-jump approved these changes

2024-05-24 13:29 UTC, merged