flamenco: system program null seed checks
firedancer-io/firedancer pull request #2060
Opened 2024-06-10 21:49 UTC by llamb-jump

https://github.com/firedancer-io/auditor-internal/issues/100

2024-06-10 21:50 UTC, llamb-jump commented on src/flamenco/runtime/program/fd_system_program.c
> +    return FD_EXECUTOR_INSTR_ERR_FATAL;
@CantelopePeel what should be returned here when these are `NULL`?

2024-06-11 14:16 UTC, closed without merging

2024-06-11 14:18 UTC, mjain-jump requested changes

2024-06-11 14:18 UTC, mjain-jump commented on src/flamenco/runtime/program/fd_system_program.c
> +    return FD_EXECUTOR_INSTR_ERR_FATAL;
If we're already this far into execution I think this check is redundant

2024-06-11 14:18 UTC, mjain-jump commented on src/flamenco/runtime/program/fd_system_program.c
> +    if( !instruction.inner.create_account_with_seed.seed || !VERIFY_SEED_UTF8( instruction.inner.create_account_with_seed.seed ) )
This shouldn't be necessary at this point - the deserialization shouldn't allow this to be null (otherwise deserializing would fail)

2024-06-11 14:18 UTC, mjain-jump commented
I don't think this PR is necessary - these null checks should be caught already before these bits get executed