flamenco: fix acceptable_reference_epoch_credits head out of bounds
firedancer-io/firedancer pull request #2064
Opened 2024-06-10 23:36 UTC by llamb-jump

2024-06-10 23:36 UTC, llamb-jump commented
https://github.com/firedancer-io/auditor-internal/issues/102

2024-06-11 09:14 UTC, topointon-jump commented on src/flamenco/runtime/program/fd_stake_program.c
> +      if( i == 0 ) break;
When you fix bugs found on fuzzing, do you mind also putting the fixture in test-vectors so we don't regress? Thanks 🙏

2024-06-11 09:27 UTC, topointon-jump requested changes
Can we add the corresponding test fixture to test-vectors, to make sure that the fix is correct and we don't regress in future? 🙏

2024-06-11 16:16 UTC, llamb-jump commented
https://github.com/firedancer-io/test-vectors/pull/20

2024-06-11 16:35 UTC, topointon-jump approved these changes

2024-06-11 16:45 UTC, merged