`CI`: on_main_push.yml: kick off solfuzz CI
firedancer-io/firedancer pull request #2067
Opened 2024-06-11 16:35 UTC by nlgripto

When a new commit lands on main, we want to kick solfuzz CI.

2024-06-11 16:44 UTC, nlgripto commented
@lheeger-jump do you want me to put the content in a separate file as the other entries in this workflow have done?

2024-06-12 10:42 UTC, topointon-jump approved these changes

2024-06-13 22:20 UTC, ripatel-fd requested changes
@nlgripto Can we use webhooks instead? (e.g. to a lambda function specified by your team). That way, the configuration is entirely on AR's side and decoupled from our CI config.

2024-06-21 15:44 UTC, ripatel-fd approved these changes

2024-06-21 16:14 UTC, merged