flamenco, fuzz: fuzz `fd_vm_validate`
firedancer-io/firedancer pull request #2113
Opened 2024-06-14 20:48 UTC by ravyu-jump

2024-06-27 21:13 UTC, ripatel-fd requested changes

2024-06-27 21:13 UTC, ripatel-fd commented on src/flamenco/runtime/tests/fd_exec_instr_test.c
This is a different component than instruction fuzzing so it should be in a different file for clarify
`fd_vm_validate_test.c` or so

2024-06-27 21:13 UTC, ripatel-fd commented on src/flamenco/runtime/tests/fd_exec_instr_test.c
> +    fd_valloc_free( valloc, fd_vm_delete( fd_vm_leave( vm ) ));
```suggestion
    fd_valloc_free( valloc, fd_vm_delete( fd_vm_leave( vm ) ) );
```

2024-06-27 21:13 UTC, ripatel-fd commented on src/flamenco/vm/fd_vm.c
> +    return FD_VM_TEXT_NOT_MULT_8;
I see you already changed it before I could submit my review. The new one is also fine :)

2024-06-27 21:14 UTC, ripatel-fd commented
@ravyu-jump Before merging, can you please squash your changes? Thanks

2024-06-27 21:15 UTC, ravyu-jump commented on src/flamenco/vm/fd_vm.c
> +    return FD_VM_TEXT_NOT_MULT_8;
lol I realized how weird it sounded as I typed out the PR description :P

2024-06-27 21:15 UTC, ravyu-jump commented on src/flamenco/runtime/tests/fd_exec_instr_test.c
> +  bool rej_callx_r10 = false;
gotcha

2024-06-28 15:21 UTC, topointon-jump submitted a review, later dismissed

2024-06-28 15:21 UTC, topointon-jump commented on src/flamenco/vm/fd_vm.c
> +     this non-guarantee is (rightfully) exploited by the fuzz harnesses. */
Can we explain why there is no corresponding link to Agave's code here?

2024-06-28 15:21 UTC, topointon-jump commented on src/flamenco/vm/fd_vm.c
> +    /* 0xc4 */ FD_CHECK_SH32, /* 0xc5 */ FD_CHECK_JMP,  /* 0xc6 */ FD_INVALID,    /* 0xc7 */ FD_CHECK_SH64,
:tada:

2024-06-28 15:21 UTC, topointon-jump commented on src/flamenco/vm/fd_vm.c
> +
```suggestion
      /* https://github.com/solana-labs/rbpf/blob/b503a1867a9cfa13f93b4d99679a17fe219831de/src/verifier.rs#L137-L139 */
      fd_sbpf_instr_t addl_imm = fd_sbpf_instr( text[ i+1UL ] );
      if( FD_UNLIKELY( addl_imm.opcode.raw!=FD_SBPF_OP_ADDL_IMM ) ) return FD_VM_ERR_LDQ_NO_ADDL_IMM;

```

2024-06-28 15:21 UTC, topointon-jump commented on src/flamenco/vm/fd_vm_base.h
> +#define FD_VM_ERR_BAD_TEXT          (-36) /* detected a bad text section */
could we elaborate in the comment what a "bad text section" could be?

2024-06-28 20:27 UTC, ravyu-jump commented on src/flamenco/runtime/tests/fd_exec_instr_test.c
> +  fd_exec_instr_ctx_t * ctx = test_vm_minimal_exec_instr_ctx( fd_libc_alloc_virtual(), rej_callx_r10 );
yeah I'll work on that with the CPI syscall fuzzer

2024-06-28 20:30 UTC, ravyu-jump commented
@ripatel-fd differences since last review: https://github.com/firedancer-io/firedancer/compare/9a12a42df...fuzz-vm-validate-unsq

2024-06-28 20:31 UTC, ravyu-jump commented
9a12a42df...fuzz-vm-validate-unsq

2024-06-28 21:18 UTC, ripatel-fd approved these changes
Thanks, looks great.

2024-06-28 21:45 UTC, merged