flamenco, vm: add reject callx r10 check in vm_validate
firedancer-io/firedancer pull request #2198
Opened 2024-06-24 22:12 UTC by ravyu-jump

Note: large chunk of the diffs are just alignment changes

2024-06-25 11:51 UTC, topointon-jump requested changes

2024-06-25 11:51 UTC, topointon-jump commented on src/flamenco/vm/fd_vm.c
> +      if( FD_UNLIKELY( instr.imm>9 ) ) return FD_VM_ERR_INVALID_REG;
We need to specifically feature gate disallowing register 10 (`reject_callx_r10`). Registers > 10 are always disallowed.

2024-06-25 21:51 UTC, ripatel-fd commented on src/flamenco/vm/instr_test/jump.instr
> +$ op=8d dst=9 src=9 imm=ffffffff reject_callx_r10   : vfy
```suggestion
reject_callx_r10=1
$ op=8d dst=9 src=9 imm=0          : err
$ op=8d dst=9 src=9 imm=1          : err
$ op=8d dst=9 src=9 imm=9          : err
$ op=8d dst=9 src=9 imm=b          : vfy
$ op=8d dst=9 src=9 imm=ffffffff   : vfy
reject_callx_r10 = 0
```

2024-06-25 22:01 UTC, ravyu-jump commented on src/flamenco/vm/instr_test/jump.instr
> +$ op=8d dst=9 src=9 imm=ffffffff reject_callx_r10   : vfy
oh good idea

2024-06-26 00:15 UTC, ripatel-fd approved these changes

2024-06-26 03:39 UTC, ravyu-jump commented
CI failed due to missing new line before EOF

2024-06-26 10:07 UTC, topointon-jump approved these changes

2024-06-26 10:07 UTC, topointon-jump approved these changes

2024-06-26 14:38 UTC, merged