[WIP] flamenco: partitioned epoch rewards
firedancer-io/firedancer pull request #2253
Opened 2024-06-28 11:00 UTC by topointon-jump

Tracking PR for the partitioned epoch rewards work.

2024-08-12 14:27 UTC, jumpsiegel approved these changes

2024-08-12 16:50 UTC, jumpsiegel submitted a review, later dismissed

2024-08-12 21:12 UTC, lheeger-jump requested changes

2024-08-12 21:12 UTC, lheeger-jump commented on src/flamenco/runtime/fd_runtime.c
> +        slot_ctx->slot_bank.block_height );
move to fd_runtime_block_execute_prepare

2024-08-13 14:42 UTC, jumpsiegel submitted a review, later dismissed

2024-08-13 14:57 UTC, ibhatt-jumptrading commented
Can we add ledger tests

2024-08-13 16:34 UTC, merged