book: generate metrics docs from xml definitions
firedancer-io/firedancer pull request #2384
Opened 2024-07-11 06:19 UTC by alpeng-jump

Closes #1011

2024-07-15 13:39 UTC, ripatel-fd commented on book/scripts/genMetrics.js
> +[THIS FILE WAS GENERATED BY generate.js. DO NOT EDIT BY HAND!]: #
Use `<!-- ... -->` for comments

2024-07-18 21:29 UTC, ripatel-fd approved these changes

2024-07-18 22:38 UTC, mmcgee-jump requested changes
Have some feedback on this that I didn't get around to yet, let's hold off on merging til I can review, sorry

2024-07-24 20:42 UTC, mmcgee-jump commented
Replaced by https://github.com/firedancer-io/firedancer/pull/2384 , I kept your author attribution let me know if you would like it removed

2024-07-24 20:42 UTC, closed without merging