deps: add missing agave dependencies
firedancer-io/firedancer pull request #2488
Opened 2024-07-22 21:11 UTC by anwayde

2024-07-22 22:39 UTC, mmcgee-jump approved these changes

2024-07-23 02:27 UTC, ripatel-fd requested changes
We depend on [pkgconf](https://packages.ubuntu.com/focal/pkgconf), not pkg-config.

2024-07-23 15:30 UTC, ripatel-fd commented
@anwayde Can you test this with a Ubuntu 22.04 VM and/or podman containers and let me know if everything is fine? 
Please note that Docker builds work just fine on main without this patch, which seems to behave differently than real hardware.

2024-07-23 15:57 UTC, ripatel-fd approved these changes

2024-07-23 16:11 UTC, merged