match sol_log_64 output
firedancer-io/firedancer pull request #2520
Opened 2024-07-26 13:51 UTC by two-heart

Currently, these are example logs from Firedancer and agave:

```
Program log: 5d724c44c0a108c8 ac246eae6b5f6c8a 7bd2aac7cd318b02 b8fb78d524538540 7a3034c712804303
Program log: 0x5d724c44c0a108c8, 0xac246eae6b5f6c8a, 0x7bd2aac7cd318b02, 0xb8fb78d524538540, 0x7a3034c712804303
```

2024-07-26 14:04 UTC, topointon-jump submitted a review, later dismissed

2024-07-26 15:19 UTC, ripatel-fd requested changes
You missed the commas

2024-07-26 15:24 UTC, two-heart commented
Oh wow, you are right 🤦 sec

2024-07-26 18:12 UTC, ripatel-fd approved these changes

2024-07-26 21:20 UTC, ripatel-fd requested changes
@two-heart Can you fix the tests? Looks like we need to increase some hardcoded size of a log buffer.

2024-07-29 19:16 UTC, ripatel-fd approved these changes

2024-07-29 19:26 UTC, merged