bank: enable extended tx metadata storage when rpc requires it
firedancer-io/firedancer pull request #2720
Opened 2024-08-15 16:09 UTC by 0x0ece

2024-08-21 17:20 UTC, mmcgee-jump commented
This should be behind the `transaction_history` config flag, not `extended_tx_metadata_storage` (you can trace this back on the Agave side to see that). But also I prefer to not modify the ABI for this, precisely because of the risk of issues like this.

Just move the `fd_ext_bank_load_and_execute_txns` to `committer.rs`, same as `fd_ext_bank_pre_balance_info` and then access `committer.transaction_status_sender_enabled()` for these fields instead.

2024-08-21 17:20 UTC, mmcgee-jump requested changes
.

2024-08-26 23:36 UTC, 0x0ece commented
Updated:
- moved `fd_ext_bank_load_and_execute_txns` to `committer.rs`
- therefore removed all other changes to fd code

2024-08-27 03:20 UTC, mmcgee-jump approved these changes

2024-08-27 14:36 UTC, merged