fix: misc fixes required to load from genesis
firedancer-io/firedancer pull request #2737
Opened 2024-08-17 22:52 UTC by arjain4

2024-08-18 11:27 UTC, ripatel-fd requested changes
https://github.com/firedancer-io/firedancer/actions/runs/10435968296/job/28900463377?pr=2737
Bank hash mismatch

2024-08-19 11:56 UTC, jumpsiegel commented on src/flamenco/runtime/fd_runtime.c
This is a surprising change

2024-08-19 18:33 UTC, arjain4 commented on src/flamenco/runtime/fd_runtime.c
>    };
that is correct, agave sets this value to 0

2024-08-19 18:35 UTC, arjain4 commented
> https://github.com/firedancer-io/firedancer/actions/runs/10435968296/job/28900463377?pr=2737 Bank hash mismatch

That ledger test uses a version of agave which has a bug related to the fees sysvar. Removing the test

2024-08-19 18:56 UTC, merged