flamenco, harness: adding better support for direct mapping
firedancer-io/firedancer pull request #2778
Opened 2024-08-22 22:31 UTC by ibhatt-jumptrading

2024-08-22 22:56 UTC, ravyu-jump requested changes

2024-08-22 22:56 UTC, ravyu-jump commented on src/flamenco/runtime/tests/fd_vm_test.c
> +    if( vm->is_deprecated-- ) {
why decrement this?

2024-08-22 22:56 UTC, ravyu-jump commented on src/flamenco/runtime/tests/fd_exec_sol_compat.c
> +  fd_log_level_logfile_set(2);
revert this

2024-08-22 22:57 UTC, ibhatt-jumptrading commented on src/flamenco/runtime/tests/fd_vm_test.c
> +    if( vm->is_deprecated-- ) {
no resizing region in deprecated loader

2024-08-22 23:03 UTC, ravyu-jump approved these changes

2024-08-23 14:37 UTC, kbhargava-jump approved these changes

2024-08-23 14:47 UTC, merged