flamenco: add ProgramCacheHitMaxLimit check
firedancer-io/firedancer pull request #2795
Opened 2024-08-26 17:51 UTC by kbhargava-jump

not ready for review. opening to check tests

2024-08-27 09:38 UTC, ripatel-fd requested changes
code style

2024-08-27 09:38 UTC, ripatel-fd commented on src/flamenco/runtime/fd_executor.c
> +    if ( memcmp( account->const_meta->info.owner, fd_solana_bpf_loader_upgradeable_program_id.uc, sizeof(fd_pubkey_t) ) == 0 ) {
```suggestion
    if( memcmp( account->const_meta->info.owner, fd_solana_bpf_loader_upgradeable_program_id.uc, sizeof(fd_pubkey_t) ) == 0 ) {
```

2024-08-27 09:38 UTC, ripatel-fd commented on src/flamenco/runtime/fd_executor.c
> +        if ( FD_LIKELY( !fd_bpf_upgradeable_loader_state_decode( &loader_state, &ctx ) ) ){
```suggestion
        if( FD_LIKELY( !fd_bpf_upgradeable_loader_state_decode( &loader_state, &ctx ) ) ){
```

2024-08-27 09:38 UTC, ripatel-fd commented on src/flamenco/runtime/fd_executor.c
> +          if ( acc_size <= PROGRAMDATA_METADATA_SIZE  ) {
```suggestion
          if( acc_size <= PROGRAMDATA_METADATA_SIZE  ) {
```

2024-08-29 05:03 UTC, ripatel-fd commented on src/flamenco/runtime/fd_executor.c
> +        if ( err ) {
code style

2024-08-29 05:03 UTC, ripatel-fd approved these changes

2024-08-29 17:56 UTC, topointon-jump commented on src/flamenco/runtime/fd_executor.c
> +        .valloc  = txn_ctx->slot_ctx->valloc,
This should be `fd_scratch_virtual()`, otherwise there is a memory leak.

2024-08-29 17:56 UTC, topointon-jump commented on src/flamenco/runtime/fd_executor.c
> +        ulong acc_size = err==FD_ACC_MGR_SUCCESS ? programdata_account->const_meta->dlen : 0UL;
`err` is always `FD_ACC_MGR_SUCCESS` as per the check above

2024-08-29 17:56 UTC, topointon-jump commented on src/flamenco/runtime/fd_executor.c
> +    fd_bpf_upgradeable_loader_state_t program_loader_state = {0};
nit: code style: make this a pointer `fd_bpf_upgradeable_loader_state_t  program_loader_state[1]`

2024-08-29 17:56 UTC, topointon-jump commented on src/flamenco/runtime/fd_executor.c
> +      fd_bpf_upgradeable_loader_state_t loader_state;
same nit

2024-08-29 18:12 UTC, topointon-jump approved these changes

2024-08-29 18:26 UTC, merged