store: disable blockstore starting from a certain slot
firedancer-io/firedancer pull request #2912
Opened 2024-09-11 08:25 UTC by anwayde

Note that there are no shreds for slot 0, so setting `disable_blockstore_from_slot = 1` has exactly the same effect as `disable_blockstore = true`.

2024-09-11 17:11 UTC, mmcgee-jump commented on src/app/fdctl/config/default.toml
> +        # A value of 0 means this option will not be used.  Any other
Could you add some commentary on what the slot number is for (aka. generating a first snapshot in benchmarking)

2024-09-11 17:11 UTC, mmcgee-jump requested changes
.

2024-09-12 16:42 UTC, ptaffet-jump commented
I think it needs to be set in the firedancer topo as well

2024-09-16 08:51 UTC, mmcgee-jump approved these changes

2024-09-16 09:08 UTC, merged