flamenco: adding special casing for non-writable non-insn accs
firedancer-io/firedancer pull request #2996
Opened 2024-09-30 20:20 UTC by ibhatt-jumptrading

2024-09-30 20:36 UTC, lheeger-jump requested changes

2024-09-30 20:36 UTC, lheeger-jump commented on src/flamenco/runtime/fd_executor.c
> +      /* If a transaction account is not an instruction account AND it is not an
fix

2024-09-30 20:36 UTC, lheeger-jump commented on src/flamenco/runtime/fd_executor.c
> +
use goto/label to jump to here

2024-10-04 13:17 UTC, ibhatt-jumptrading commented
combined with pr that fixes several bugs with transaction loading

2024-10-04 13:17 UTC, closed without merging