bundle: add support for retrieving bundles from a block engine
firedancer-io/firedancer pull request #3036
Opened 2024-10-04 15:14 UTC by mmcgee-jump

2025-01-16 10:00 UTC, two-heart requested changes

2025-01-16 10:00 UTC, two-heart commented on plugin/bundle/src/block_engine_stage.rs
> +        // but unfortuantely the libraries require Tokio to use some of
```suggestion
        // but unfortunately the libraries require Tokio to use some of
```

2025-01-16 10:25 UTC, two-heart commented on src/app/fdctl/run/tiles/bundle.seccomppolicy
> +#         reveiver needs them.
```suggestion
#         receiver needs them.
```

2025-01-28 22:03 UTC, ptaffet-jump commented on src/app/fdctl/run/tiles/fd_bundle.c
> +    if( FD_LIKELY( i ) ) {
I may be confused, but isn't this backwards?  I'm not sure how this worked.

> if this transaction is the first one in the
> bundle, bundle_txn_cnt will be non-zero.

2025-01-28 22:47 UTC, ptaffet-jump commented on src/app/fdctl/run/tiles/fd_dedup.c
> +  int is_dup = 0;
See comments in slack

2025-02-06 20:16 UTC, closed without merging

2025-02-06 20:16 UTC, ptaffet-jump commented
Rolled into #4114