feat(eqvoc): equivocation tile
firedancer-io/firedancer pull request #3082
Opened 2024-10-10 14:45 UTC by lidatong

2024-10-10 16:56 UTC, mmcgee-jump commented
Why is this a tile? Is it expensive to do this work?

2024-10-11 13:26 UTC, lidatong commented
> Why is this a tile? Is it expensive to do this work?

it has to examine every shred (before resolving the fec set) as well rx / tx potentially spammy gossip msgs

2024-10-16 14:40 UTC, lheeger-jump requested changes

2024-10-16 14:40 UTC, lheeger-jump commented on contrib/test/setup_fd_cluster.sh
> +rm -rf ../test-ledger
rm

2024-10-16 14:40 UTC, lheeger-jump commented on contrib/test/setup_fd_cluster.sh
> +GENESIS_OUTPUT=$(/data/chali/agave/release/solana-genesis \
make parameterizeable with reasonable default

2024-10-16 14:40 UTC, lheeger-jump commented on contrib/test/setup_fd_cluster.sh
> +RUST_LOG=debug /data/chali/agave/release/agave-validator \
ditto

2024-10-16 15:42 UTC, lheeger-jump approved these changes

2024-10-16 15:55 UTC, merged