tiles: rewrite mux to stem
firedancer-io/firedancer pull request #3090
Opened 2024-10-11 06:46 UTC by mmcgee-jump

2024-10-12 21:00 UTC, ripatel-fd requested changes
Large refactors like these should come with unit tests. 
fd_stem doesn't appear to have any test coverage

2024-10-14 20:22 UTC, mmcgee-jump commented
That's coming in a separate change, this is getting too big.

2024-10-15 10:30 UTC, ripatel-fd commented
> That's coming in a separate change, this is getting too big.

Changing test_mux to test_stem instead of deleting it might reduce the diff

2024-10-15 15:15 UTC, mmcgee-jump commented
That test is a bit limited, and it also didn't run in CI.

2024-10-16 05:12 UTC, mmcgee-jump commented
todo: switch the printer for counter/gauge to use converter as well

2024-10-16 15:21 UTC, ptaffet-jump approved these changes
I looked at `fd_stem` a little, and the rest of the PR almost not at all, but I'm stamping to unblock

2024-10-16 15:21 UTC, ptaffet-jump commented on src/disco/stem/fd_stem.c
> +  ulong cr_min = fd_ulong_if( !out_cnt, 128UL, ULONG_MAX );
Maybe call this `depth_min`

2024-10-16 15:21 UTC, ptaffet-jump commented on src/disco/stem/fd_stem.c
> +  ulong cr_min = fd_ulong_if( !out_cnt, 128UL, ULONG_MAX );
And then keep the variable formerly called `cr_max`. It's just confusing to see a variable change names from `cr_max` to `cr_min` without changing roles

2024-10-16 21:27 UTC, lheeger-jump approved these changes

2024-10-16 21:41 UTC, ripatel-fd submitted a review, later dismissed

2024-10-16 21:42 UTC, ripatel-fd commented
Kicking CI to rerun failed jobs. (flaky CI environment)

2024-10-16 22:47 UTC, ripatel-fd approved these changes

2024-10-17 15:22 UTC, ptaffet-jump approved these changes
Restamping

2024-10-17 15:40 UTC, merged