quic - changed defaults.toml max_concurrent_handshakes description and value
firedancer-io/firedancer pull request #3124
Opened 2024-10-14 21:34 UTC by nbridge-jump

`max_concurrent_handshakes` is no longer bound to the value of `max_concurrent_connections`. So this PR fixes the description and sets the value to a conservative number.

2024-10-14 21:50 UTC, mmcgee-jump commented
Can you update the default for `max_concurrent_connections` to be correct as well?

2024-10-14 21:50 UTC, mmcgee-jump requested changes
.

2024-10-14 22:10 UTC, nbridge-jump commented
> Can you update the default for `max_concurrent_connections` to be correct as well?

I'm not sure what you're asking for. This value isn't being used in mainnet. Is that what you want?

2024-10-14 22:21 UTC, mmcgee-jump commented
The default values we provide should be sane for mainnet, which 2048 for max_concurrent_connections clearly is not.

2024-10-14 22:40 UTC, nbridge-jump commented
> The default values we provide should be sane for mainnet, which 2048 for max_concurrent_connections clearly is not.

Just accept this PR. Increasing max_concurrent_connections to mainnet levels broke some tests. So I'll work on fixing all that in another PR. No need to hold up this change, which is clearly an improvement on main

2024-10-14 23:08 UTC, nbridge-jump commented
Ignore that. Looks like the issue was already solved. Will squash the commits

2024-10-15 15:18 UTC, mmcgee-jump approved these changes

2024-10-15 15:29 UTC, merged