quic: use random TLS public key
firedancer-io/firedancer pull request #3352
Opened 2024-11-07 15:53 UTC by ripatel-fd

Agave TPU clients ignore the server's TLS public key.
Thus, we can generate a random throwaway key on startup instead of
reusing the identity key.  This improves our security architecture
and removes a potential performance bottleneck with the keyguard tile.

2024-11-07 19:01 UTC, nbridge-jump approved these changes
Nice
LGTM

2024-11-07 19:08 UTC, mmcgee-jump requested changes
Can't you also remove FD_KEYGUARD_PAYLOAD_TLS_CV and all the related code (e.g. ambiguity proof etc?)

2024-11-08 06:33 UTC, ripatel-fd commented
> Can't you also remove FD_KEYGUARD_PAYLOAD_TLS_CV and all the related code (e.g. ambiguity proof etc?)

@mmcgee-jump I think we should keep this logic. We'll need it for client-side code in the future. When sending transactions to Agave servers, you get better quotas if you authenticate yourself with the identity key.

2024-11-08 06:50 UTC, mmcgee-jump commented
We can just bring the code back then? I don't mind leaving things in place that aren't security sensitive, but any surface area reduction in signing tile is a win.

2024-11-08 07:51 UTC, two-heart approved these changes
lgtm from a security pov

2024-11-09 05:29 UTC, ripatel-fd commented
> We can just bring the code back then? I don't mind leaving things in place that aren't security sensitive, but any surface area reduction in signing tile is a win.

@mmcgee-jump  I removed the authorize logic from the keyguard. The ambiguity detection logic should stay in, since anytime we change that, we have to rerun CBMC proofs. The full validator team is about to use this code any minute. They will need a QUIC client to implement the submitTransaction RPC. 

This is a big improvement as-is, let's merge it first? And if nobody uses that signing payload ambiguity logic in a month, we can always remove it later.

2024-11-09 10:02 UTC, mmcgee-jump approved these changes

2024-11-09 10:52 UTC, merged