sbpf: loader improvements
firedancer-io/firedancer pull request #356
Opened 2023-05-20 05:03 UTC by ripatel-jump

- utf8: add fd_utf8_check_cstr
- sbpf: loader refactor and improvements
  - add UTF-8 validation
  - move rodata segment into separate memory region
    and remove zero-copy / masking logic
  - fix various diff fuzz findings

2023-05-22 17:39 UTC, lheeger-jump requested changes

2023-05-22 17:39 UTC, lheeger-jump commented on src/ballet/sbpf/fd_sbpf_opcode.h
> +#ifndef HEADER_fd_src_ballet_sbpf_fd_sbpf_opcode_h
This is duplicate with fd_sbpf_opcodes.h. What is your intent with this file?

2023-05-22 17:39 UTC, lheeger-jump commented
Can you move the UTF8 validation to its own PR?

2023-05-24 19:26 UTC, ripatel-fd commented
@lheeger-jump done, new PR is here: https://github.com/firedancer-io/firedancer/pull/379

(btw, this was already split out on the commit level, and would have created two separate commits on main if merged as-is. But I understand that splitting it into separate PRs makes it easier to review)

2023-05-24 23:02 UTC, lheeger-jump approved these changes

2023-05-24 23:03 UTC, merged