add TLS keylog parser
firedancer-io/firedancer pull request #430
Opened 2023-06-07 04:09 UTC by ripatel-fd

From milestone 1.1

2023-06-07 14:37 UTC, mmcgee-jump commented on src/ballet/tls/fuzz_tls_keylog_parse.c
> +LLVMFuzzerInitialize( int  *   argc,
If this is just for test / development, why did we write a fuzzer? Is that comment still accurate?

2023-06-07 14:41 UTC, mmcgee-jump requested changes
Can you clarify why this is here or what it's used for? There's not even any way to call the code?

2023-06-07 17:42 UTC, mmcgee-jump commented
Discussed with Richie, this is used for decrypting `pcapng` files so we can feed them back into Firedancer as a simulation. It's not for production use in live Firedancer itself.

Suggest sticking it in a different lib than `ballet` (eg a new`testutil` library) before merging.

2023-07-20 23:53 UTC, ripatel-fd commented
We won't need this if we implement qlog (#317), which also provides access to decrypted frames

2023-07-20 23:53 UTC, closed without merging